### PR TITLE
Update to 5.0.0

### PR DESCRIPTION
**Pull request by xoviat**
Closes #21.

### CODE REVIEW

**Comment by xoviat** [comment]
@isuruf Can you fix the patch?

**Comment by isuruf** [comment]
Okay. I will

**Comment by isuruf** [comment]
@jakirkham, @inducer, can you have a look? I'd like to get this in before travis-ci gets busy.

**Comment by inducer** [comment]
I believe the calling convention patch was merged upstream:

* https://reviews.llvm.org/D33639
* https://github.com/pocl/pocl/issues/1

@isuruf Could you check to make sure and then just drop it?

**Comment by xoviat** [comment]
Yes, I noted that in my first commit message.

**Comment by inducer** [comment]
LGTM aside from the OpenCL CC patch issue.

**Comment by xoviat** [comment]
The OpenCL patch is removed. There is another patch related to libxml2, which is still required.

**Comment by inducer** [comment]
> The OpenCL patch is removed

IMO, it ought to be deleted and the line removed from `meta.yml`.

**Comment by xoviat** [comment]
Done.

**Comment by isuruf** [comment]
Tests pass now

**Comment by inducer** [comment]
@SylvainCorlay, sorry--nvm. I realized that the cling variant got left behind at 4.0 already, so there's no need to hold up 5.0 based on it. Sorry for the noise.

**Comment by inducer** [comment]
@xoviat @isuruf Thanks for working on this!

**Comment by xoviat** [comment]
@inducer We still need to add the flang variant. Should it go in this branch or another one?

**Comment by xoviat** [comment]
There are two changes:
- 1. Updating to 5.0 (this one)
- 2. adding NVIDIA's hacked clang

**Comment by inducer** [comment]
I created the flang branch for you. I tend to agree with @isuruf that a separate branch is probably best, since it doesn't look like we necessarily want to update clang whenever flang updates and vice versa, plus it uses a different package source.

**Pull request merged**
