### PR TITLE
Update 5.x variant for ROOT 6.22 patches

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge/clangdev Ready for review!

**Comment by chrisburr** [comment]
@conda-forge/clangdev Can someone take a look

**Comment by chrisburr** [comment]
@conda-forge/clangdev @conda-forge/core Can someone merge this? The release of ROOT has been tagged so this is now blocking conda-forge/root-feedstock#89.

**Comment by beckermr** [comment]
Please add yourself as a maintainer. Then we can merge.

**Comment by chrisburr** [comment]
It won't apply as this is targetting an older branch but I can do that in another PR

**Comment by chrisburr** [comment]
Thanks @beckermr! 🍰

**Pull request merged**
