### PR TITLE
Rebuild 5.x

### PR DESCRIPTION
**Pull request by JohanMabille**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by JohanMabille** [comment]
> This picks up header of libxml2 from the base environment. You probably want [ddf8b3b](https://github.com/conda-forge/clangdev-feedstock/commit/ddf8b3bcf67a29a8945cef68d25ed3a61a17c588) , i.e., `-DLLVM_ENABLE_LIBXML2=OFF`.

Thanks!

**Comment by JohanMabille** [comment]
Looks lke llvm is too old to take into account this option. Let's copy iconv headers ...

**Comment by h-vetinari** [comment]
Out of curiosity, which package(s) still specifically need a [5 year old](https://github.com/llvm/llvm-project/tags?after=llvmorg-6.0.0) compiler?

**Comment by JohanMabille** [comment]
cling 0.8

**Comment by JohanMabille** [comment]
No need for this anymore.

**Pull request closed without merging**
