### PR TITLE
Improve sysroot detection and use ROOT's fork for cling's patches

### PR DESCRIPTION
**Pull request by chrisburr**
Includes the sysroot detection improvements in #45.

This PR downloads the clang source from ROOT's fork for the cling variants. Additionally, the build string for `clang_variant` now contains the version of ROOT from which the patches have been taken:

* `default`
* `cling_6.14.06`
* `cling_6.16.00`

The motivation for this change is:

* There is quite a lot of patches to maintain
* It is likely new ones will keep appearing
* The build number no longer needs to be bumped as a new variant can be added instead
* The `clang_variant` package allows the patch set to be "versioned" without adding fake version numbers for conda-forge. This should avoid problems with ABI changes.

### CODE REVIEW

**Comment by chrisburr** [comment]
@SylvainCorlay I've built and tested both `root`/`cling` based on this PR and everything seems okay so I think this is ready to merge if you're happy? I'll then make a PR for an updated cling build.

Longer term, I hope this situation can be improved once ROOT moves to clang 7. Ideally with a clean set of patches being provided rather then vendoring the entirety of clang.

**Comment by chrisburr** [comment]
Alternatively, I can revert back to having the full list of patches, and using jinja2 features to provide the versioned cling variants like `cling_6.14.06` and `cling_6.16.00`.

**Comment by chrisburr** [comment]
Any thoughts @SylvainCorlay?

**Comment by SylvainCorlay** [comment]
I have some questions about the move to the root fork

 - Should there be a build of cling for each cling_* variant?
 - should we delete the cling and root patches from this repository then?

**Comment by chrisburr** [comment]
> Should there be a build of cling for each cling_* variant?

I think different versions of cling should use different `cling_*` variants. i.e. `cling=0.5` will use `cling_6.14.06` and `cling=0.6` (unreleased) will use `cling_6.16.00`.
 
> should we delete the cling and root patches from this repository then?

Yeah, I just wanted to check you were happy with this approach before deleting them.

**Comment by SylvainCorlay** [comment]
🎉 👍 💯

**Comment by chrisburr** [comment]
Thanks! Once this is deployed I'll make a PR to cling.

**Comment by SylvainCorlay** [comment]
> > should we delete the cling and root patches from this repository then?
>
> Yeah, I just wanted to check you were happy with this approach before deleting them.

Thanks for this. Unfortunately, I don't think that there is an ideal solution.

**Pull request merged**
