### PR TITLE
[9.x] build root variant for windows

### PR DESCRIPTION
**Pull request by saraedum**
as a prerequisite for https://github.com/conda-forge/cppyy-cling-feedstock/issues/1.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@conda-forge/clangdev does somebody know how I can get rid of `relocation truncated to fit: R_PPC64_REL24` on ppc64?

I hacked build.sh a bit to get all compiling and linking to add `-Os -mcmodel=medium` and used the latest compiler but that does not seem to do the trick. Namely, when linking the clang executable with the following command:

```
2021-09-04T12:08:37.1528455Z $BUILD_PREFIX/bin/powerpc64le-conda-linux-gnu-c++ -fvisibility-inlines-hidden -fmessage-length=0 -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/clang_packages-9.0.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -mcmodel=medium -Os -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -pedantic -Wno-long-long -O3 -DNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -mcmodel=medium -Os -Wl,-Os -Wl,--export-dynamic -rdynamic  -Wl,-rpath-link,$SRC_DIR/build/./lib  -Wl,-O3 CMakeFiles/clang.dir/driver.cpp.o CMakeFiles/clang.dir/cc1_main.cpp.o CMakeFiles/clang.dir/cc1as_main.cpp.o CMakeFiles/clang.dir/cc1gen_reproducer_main.cpp.o -o ../../bin/clang-9  -Wl,-rpath,"\$ORIGIN/../lib" $PREFIX/lib/libLLVMAArch64CodeGen.a $PREFIX/lib/libLLVMAArch64AsmParser.a $PREFIX/lib/libLLVMAArch64Desc.a $PREFIX/lib/libLLVMAArch64Disassembler.a $PREFIX/lib/libLLVMAArch64Info.a $PREFIX/lib/libLLVMAArch64Utils.a $PREFIX/lib/libLLVMAMDGPUCodeGen.a $PREFIX/lib/libLLVMAMDGPUAsmParser.a $PREFIX/lib/libLLVMAMDGPUDesc.a $PREFIX/lib/libLLVMAMDGPUDisassembler.a $PREFIX/lib/libLLVMAMDGPUInfo.a $PREFIX/lib/libLLVMAMDGPUUtils.a $PREFIX/lib/libLLVMARMCodeGen.a $PREFIX/lib/libLLVMARMAsmParser.a $PREFIX/lib/libLLVMARMDesc.a $PREFIX/lib/libLLVMARMDisassembler.a $PREFIX/lib/libLLVMARMInfo.a $PREFIX/lib/libLLVMARMUtils.a $PREFIX/lib/libLLVMBPFCodeGen.a $PREFIX/lib/libLLVMBPFAsmParser.a $PREFIX/lib/libLLVMBPFDesc.a $PREFIX/lib/libLLVMBPFDisassembler.a $PREFIX/lib/libLLVMBPFInfo.a $PREFIX/lib/libLLVMHexagonCodeGen.a $PREFIX/lib/libLLVMHexagonAsmParser.a $PREFIX/lib/libLLVMHexagonDesc.a $PREFIX/lib/libLLVMHexagonDisassembler.a $PREFIX/lib/libLLVMHexagonInfo.a $PREFIX/lib/libLLVMLanaiCodeGen.a $PREFIX/lib/libLLVMLanaiAsmParser.a $PREFIX/lib/libLLVMLanaiDesc.a $PREFIX/lib/libLLVMLanaiDisassembler.a $PREFIX/lib/libLLVMLanaiInfo.a $PREFIX/lib/libLLVMMipsCodeGen.a $PREFIX/lib/libLLVMMipsAsmParser.a $PREFIX/lib/libLLVMMipsDesc.a $PREFIX/lib/libLLVMMipsDisassembler.a $PREFIX/lib/libLLVMMipsInfo.a $PREFIX/lib/libLLVMMSP430CodeGen.a $PREFIX/lib/libLLVMMSP430AsmParser.a $PREFIX/lib/libLLVMMSP430Desc.a $PREFIX/lib/libLLVMMSP430Disassembler.a $PREFIX/lib/libLLVMMSP430Info.a $PREFIX/lib/libLLVMNVPTXCodeGen.a $PREFIX/lib/libLLVMNVPTXDesc.a $PREFIX/lib/libLLVMNVPTXInfo.a $PREFIX/lib/libLLVMPowerPCCodeGen.a $PREFIX/lib/libLLVMPowerPCAsmParser.a $PREFIX/lib/libLLVMPowerPCDesc.a $PREFIX/lib/libLLVMPowerPCDisassembler.a $PREFIX/lib/libLLVMPowerPCInfo.a $PREFIX/lib/libLLVMRISCVCodeGen.a $PREFIX/lib/libLLVMRISCVAsmParser.a $PREFIX/lib/libLLVMRISCVDesc.a $PREFIX/lib/libLLVMRISCVDisassembler.a $PREFIX/lib/libLLVMRISCVInfo.a $PREFIX/lib/libLLVMRISCVUtils.a $PREFIX/lib/libLLVMSparcCodeGen.a $PREFIX/lib/libLLVMSparcAsmParser.a $PREFIX/lib/libLLVMSparcDesc.a $PREFIX/lib/libLLVMSparcDisassembler.a $PREFIX/lib/libLLVMSparcInfo.a $PREFIX/lib/libLLVMSystemZCodeGen.a $PREFIX/lib/libLLVMSystemZAsmParser.a $PREFIX/lib/libLLVMSystemZDesc.a $PREFIX/lib/libLLVMSystemZDisassembler.a $PREFIX/lib/libLLVMSystemZInfo.a $PREFIX/lib/libLLVMWebAssemblyCodeGen.a $PREFIX/lib/libLLVMWebAssemblyAsmParser.a $PREFIX/lib/libLLVMWebAssemblyDesc.a $PREFIX/lib/libLLVMWebAssemblyDisassembler.a $PREFIX/lib/libLLVMWebAssemblyInfo.a $PREFIX/lib/libLLVMX86CodeGen.a $PREFIX/lib/libLLVMX86AsmParser.a $PREFIX/lib/libLLVMX86Desc.a $PREFIX/lib/libLLVMX86Disassembler.a $PREFIX/lib/libLLVMX86Info.a $PREFIX/lib/libLLVMX86Utils.a $PREFIX/lib/libLLVMXCoreCodeGen.a $PREFIX/lib/libLLVMXCoreDesc.a $PREFIX/lib/libLLVMXCoreDisassembler.a $PREFIX/lib/libLLVMXCoreInfo.a $PREFIX/lib/libLLVMAnalysis.a $PREFIX/lib/libLLVMCodeGen.a $PREFIX/lib/libLLVMCore.a $PREFIX/lib/libLLVMipo.a $PREFIX/lib/libLLVMAggressiveInstCombine.a $PREFIX/lib/libLLVMInstCombine.a $PREFIX/lib/libLLVMInstrumentation.a $PREFIX/lib/libLLVMMC.a $PREFIX/lib/libLLVMMCParser.a $PREFIX/lib/libLLVMObjCARCOpts.a $PREFIX/lib/libLLVMOption.a $PREFIX/lib/libLLVMScalarOpts.a $PREFIX/lib/libLLVMSupport.a $PREFIX/lib/libLLVMTransformUtils.a $PREFIX/lib/libLLVMVectorize.a -lpthread ../../lib/libclangBasic.a ../../lib/libclangCodeGen.a ../../lib/libclangDriver.a ../../lib/libclangFrontend.a ../../lib/libclangFrontendTool.a ../../lib/libclangSerialization.a $PREFIX/lib/libLLVMAArch64Desc.a $PREFIX/lib/libLLVMAArch64Info.a $PREFIX/lib/libLLVMAArch64Utils.a $PREFIX/lib/libLLVMMIRParser.a $PREFIX/lib/libLLVMAMDGPUDesc.a $PREFIX/lib/libLLVMAMDGPUInfo.a $PREFIX/lib/libLLVMAMDGPUUtils.a $PREFIX/lib/libLLVMARMDesc.a $PREFIX/lib/libLLVMARMInfo.a $PREFIX/lib/libLLVMARMUtils.a $PREFIX/lib/libLLVMHexagonDesc.a $PREFIX/lib/libLLVMHexagonInfo.a $PREFIX/lib/libLLVMLanaiDesc.a $PREFIX/lib/libLLVMLanaiInfo.a $PREFIX/lib/libLLVMSystemZDesc.a $PREFIX/lib/libLLVMSystemZInfo.a $PREFIX/lib/libLLVMWebAssemblyDesc.a $PREFIX/lib/libLLVMWebAssemblyInfo.a $PREFIX/lib/libLLVMGlobalISel.a $PREFIX/lib/libLLVMAsmPrinter.a $PREFIX/lib/libLLVMDebugInfoDWARF.a $PREFIX/lib/libLLVMSelectionDAG.a $PREFIX/lib/libLLVMMCDisassembler.a ../../lib/libclangCodeGen.a $PREFIX/lib/libLLVMCoroutines.a $PREFIX/lib/libLLVMCoverage.a $PREFIX/lib/libLLVMLTO.a $PREFIX/lib/libLLVMObjCARCOpts.a $PREFIX/lib/libLLVMPasses.a $PREFIX/lib/libLLVMCodeGen.a $PREFIX/lib/libLLVMipo.a $PREFIX/lib/libLLVMLinker.a $PREFIX/lib/libLLVMBitWriter.a $PREFIX/lib/libLLVMIRReader.a $PREFIX/lib/libLLVMAsmParser.a $PREFIX/lib/libLLVMInstrumentation.a $PREFIX/lib/libLLVMScalarOpts.a $PREFIX/lib/libLLVMAggressiveInstCombine.a $PREFIX/lib/libLLVMInstCombine.a $PREFIX/lib/libLLVMVectorize.a $PREFIX/lib/libLLVMTransformUtils.a $PREFIX/lib/libLLVMTarget.a $PREFIX/lib/libLLVMAnalysis.a $PREFIX/lib/libLLVMObject.a ../../lib/libclangRewriteFrontend.a ../../lib/libclangARCMigrate.a ../../lib/libclangStaticAnalyzerFrontend.a ../../lib/libclangStaticAnalyzerCheckers.a ../../lib/libclangStaticAnalyzerCore.a ../../lib/libclangCrossTU.a ../../lib/libclangIndex.a ../../lib/libclangFrontend.a ../../lib/libclangDriver.a $PREFIX/lib/libLLVMOption.a $PREFIX/lib/libLLVMProfileData.a ../../lib/libclangParse.a $PREFIX/lib/libLLVMMCParser.a ../../lib/libclangSerialization.a $PREFIX/lib/libLLVMBitReader.a ../../lib/libclangSema.a ../../lib/libclangAnalysis.a ../../lib/libclangASTMatchers.a ../../lib/libclangEdit.a $PREFIX/lib/libLLVMBitstreamReader.a ../../lib/libclangFormat.a ../../lib/libclangToolingInclusions.a ../../lib/libclangToolingCore.a ../../lib/libclangAST.a ../../lib/libclangRewrite.a ../../lib/libclangLex.a ../../lib/libclangBasic.a $PREFIX/lib/libLLVMCore.a $PREFIX/lib/libLLVMRemarks.a $PREFIX/lib/libLLVMMC.a $PREFIX/lib/libLLVMBinaryFormat.a $PREFIX/lib/libLLVMDebugInfoCodeView.a $PREFIX/lib/libLLVMDebugInfoMSF.a $PREFIX/lib/libLLVMSupport.a $PREFIX/lib/libLLVMDemangle.a -lrt -ldl -lpthread -lm 
```

we get the following error:
```
2021-09-04T12:08:47.2338684Z TargetInfo.cpp:(.text._ZL15getRecordArgABIPKN5clang10RecordTypeERNS_7CodeGen8CGCXXABIE+0x34): relocation truncated to fit: R_PPC64_REL24 against symbol `clang::TagType::getDecl() const' defined in .text._ZNK5clang7TagType7getDeclEv section in ../../lib/libclangAST.a(Type.cpp.o)
```

I have to admit I don't have a good understanding of what's the problem here. In any case, this is only an artifact of rerendering the feedstock and completely unrelated to the aim of this PR. (Same problem happened for #124.)

**Comment by SylvainCorlay** [comment]
@saraedum I am seeing the same issue on the other build for the cling variant. No idea how we could fix it.

**Comment by SylvainCorlay** [comment]
@saraedum it seems that the latest build for llvmdev 9.x on ppc is quite old and was done with an earlier version of gcc.

**Comment by SylvainCorlay** [comment]
Yep, this could be it. From the gcc changelog:

```
Linking medium model libraries (or objects) compiled with new compiler into medium model program compiled with older
 will likely result in exceeding ranges of relocations.
```

**Comment by saraedum** [comment]
@SylvainCorlay thanks for having a look. Great, once we get your MR on llvmdev merged, we should try again here.

**Comment by saraedum** [comment]
> Yep, this could be it. From the gcc changelog:
> 
> ```
> Linking medium model libraries (or objects) compiled with new compiler into medium model program compiled with older
>  will likely result in exceeding ranges of relocations.
> ```

Hm…then again, isn't that the other way round here? Are we actually building llvmdev with mcmodel=medium?

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
@isuruf trying to pin the compiler to GCC 8 like in llvmdev produces:
```
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/conda/feedstock_root/build_artifacts/clang_packages_1631278392159/_build_env/bin/x86_64-conda-linux-gnu-cc)
    gmake[4]: *** [CMakeFiles/cmTC_f3958.dir/testCCompiler.c.o] Error 1
```

**Comment by isuruf** [comment]
Remove https://github.com/conda-forge/clangdev-feedstock/blob/9.x/conda-forge.yml#L9

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by SylvainCorlay** [comment]
Why gcc 8 and not gcc 9.3.

**Comment by saraedum** [comment]
> Why gcc 8 and not gcc 9.3.

I don't know. It makes the error go away.

**Comment by SylvainCorlay** [comment]
> > Why gcc 8 and not gcc 9.3.
>
> I don't know. It makes the error go away.

I was asking because the last succesful build was with gcc 9.3, and this issue appeared with gcc 9.4.

**Comment by SylvainCorlay** [comment]
@saraedum in #145 (essentially the same PR adding the cling variant), I was able to make it work with gcc 9.3.

It may be less disruptive than pinning to gcc 8.

**Comment by saraedum** [comment]
This needs to be rebased to version 13.

**Pull request closed without merging**
