### PR TITLE
Release 3.9.1

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
This is ready to be merged!

**Comment by SylvainCorlay** [comment]
It seems that I still cannot have merge privileges, but I would like to take advantage of the low travis-ci load of the week end.

**Comment by SylvainCorlay** [comment]
@jakirkham would you be ok merging this? I would like to take advantage of the low travis ci loads of the week end.

**Comment by jakirkham** [comment]
Sure. Though I'm about to board a plane. So may not be able to do much merging afterwards.

**Pull request merged**
