### PR TITLE
Provide specific about sections

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
So why does conda-smithy pick up the `about` section of `clang` for `README.md`?

**Comment by saraedum** [comment]
@isuruf: Here's the promised PR. Unfortunately, the linter does not want me to pull the about section up to before the outputs. And conda-smithy does not handle this correctly yet. But otherwise this might be good to go.

**Comment by timsnyder** [comment]
Oh, this is a nicer way to do specific about sections than the way I've been doing it (where there is a ton of copied content in all of the about sections).  @saraedum, did you propose a PR to conda-smithy to handle this?

I was just thinking that it would be really great to have specific about sections because I can't remember which package `clang-tidy` is ending up in.

**Comment by saraedum** [comment]
> @saraedum, did you propose a PR to conda-smithy to handle this?

No, I didn't. But that was a long time ago. Maybe it's fixed by now?

**Comment by saraedum** [comment]
The meta.yaml has diverged too far for this to be mergeable. If we still want this, we should do this in a new PR.

**Pull request closed without merging**
