### PR TITLE
[9.x] Add missing patches for the conda-forge sysroot on Linux

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Can you explain what's going on here?

**Comment by chrisburr** [comment]
These patches are copied from the `5.x` branch. I thought they might be possible to avoid thanks to the newer patches that make clang aware of `CONDA_BUILD_SYSROOT` but this crash in `root`/`cling` has shown up in a couple of places:

```cpp
root.exe: /home/conda/feedstock_root/build_artifacts/root_base_1618934087320/work/
root-source/interpreter/cling/lib/Interpreter/CIFactory.cpp:595:
{anonymous}::collectModuleMaps(clang::CompilerInstance&, llvm::SmallVectorImpl<std::__cxx11::basic_string<char> >&)::<lambda(llvm::StringRef, const string&, const string&, std::string&, bool, bool)>:
Assertion `llvm::sys::fs::exists(SystemDir) && "Must exist!"' failed.
```

The cause is from `CONDA_BUILD_SYSROOT` not being set due to `PATH` being modified directly instead of calling `conda activate ...`. Obviously people should be activating environments properly but it's a common enough issue that I want `root`/`cling` to still be functional, especially as it's harder to correctly call `conda activate` in places like docker containers and jupyter kernels.

(The force push was to remove a duplicated file but this is ready to merge)

**Comment by chrisburr** [comment]
@isuruf If you have no objections I'll merge this in a few hours.

(Comment/leave a reaction if you want me to wait until you have a chance to take a proper look.)

**Comment by isuruf** [comment]
`CONDA_BUILD_SYSROOT` is the first search option. If that's not available, then it looks for the sysroot relative to the binary. https://github.com/conda-forge/clangdev-feedstock/blob/9.x/recipe/patches/0001-Find-conda-gcc-installation.patch should work right?

**Comment by isuruf** [comment]
If that doesn't work, the correct way would be to set `-DDEFAULT_SYSROOT=/path/to/sysroot`.
(To fix the binary replacement issue, you can add `SysRoot = std::string(SysRoot.c_str())`)

**Pull request closed without merging**
