### PR TITLE
Fix clang-format

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc @henryiii

### CODE REVIEW

**Comment by henryiii** [comment]
Nice, was just trying this. This is what I was about to try:

```bash
#!/bin/bash
set -x -e
source install_clang_tools.sh

for f in ${PREFIX}/bin/*; do
    if [[ "$f" !=  "*clang-format-${MAJOR_VERSION}" ]]; then
        rm $f
    fi
done
```

**Comment by isuruf** [comment]
https://github.com/conda/conda-build/pull/4281

**Comment by henryiii** [comment]
Looks like this is failing:
```
/Users/runner/miniforge3/conda-bld/clang_packages_1631807490112/test_tmp/run_test.sh: line 7: clang-format-12: command not found
```

**Comment by henryiii** [comment]
Fantastic, this is now small enough to run in pre-commit.ci! :tada:

```
local:--channel=conda-forge,clang-format==12.0.1 (15.4KiB) (cached)
  envs:
  - conda@default (202.2MiB) (built)
```

For now:

```yaml
  - id: clang-format
     name: Clang Format
     language: conda
     types: [c++]
     entry: clang-format
     args: [-style=file, -i]
     additional_dependencies: [--channel=conda-forge, clang-format==12.0.1]
```

Looking at making a proper hook repo somewhere next.

**Pull request merged**
