### PR TITLE
Add cling patches

### PR DESCRIPTION
**Pull request by SylvainCorlay**
The goal is to package the cling C++ interpreter from CERN on conda-forge, which requires applying patches to llvm and clang.

This creates a new flavor for this package, only used when the cling-patches feature is active, in which a few patches are applied on the llvm source tree.

Instead of squashing the patches together, I apply them separately so that it is easy to track when some are added or removed.

I will add the LLVM_VARIANT to the build matrix in a later commit.

The llvm package will also use the same feature (https://github.com/conda-forge/llvmdev-feedstock/pull/4).

The cling package is the one that will provide the track_feature statement.

@msarahan is this the right way to go with this?

### CODE REVIEW

**Comment by jakirkham** [comment]
So I have heard about different patches to clang and llvm for loads of different use cases. It sounds like a good idea to support a few of the common ones (cling included). Maybe we should have some discussion on how we want to manage these variants.

**Comment by SylvainCorlay** [comment]
@jakirkham thanks for pitching in, this is really my goal here, to find a path forward for packaging cling.

This is my first use of conda "features" so let me know if a better approach would be more appropriate.

**Comment by inducer** [comment]
Would you think it is possible to keep these patches in a for-cling (or some-such) subfolder?

**Comment by SylvainCorlay** [comment]
@inducer totally, that is a good idea. I will move the patches of llvm too.

**Comment by inducer** [comment]
> totally, that is a good idea. I will move the llvm patches too.

Thx!

**Comment by SylvainCorlay** [comment]
OK, I moved all the patches to a cling-patches directory, which is also the name of the clang branch holding the patches and now the name of the conda feature.

**Comment by inducer** [comment]
One possible concern here is that `llvmdev` is currently at 3.9.x, but `clangdev` is still at 3.8.1. (I wanted to have a build of 3.8 available, that's why I submitted that one first.) I imagine in order for meaningful work to be accomplished, you likely want both versions synchronized. (So we should queue up the clang update to 3.9 before this goes in.)

**Comment by SylvainCorlay** [comment]
Absolutely. it seems that these patches require 3.9 anyway.

**Comment by SylvainCorlay** [comment]
Should I open a separate PR on updating to 3.9 first and rebase this one on the top of it?

**Comment by inducer** [comment]
> Should I open a separate PR on updating to 3.9 first

Yes, I think that makes the most sense.

**Comment by SylvainCorlay** [comment]
The link errors seem to be related to the linking with non-patched llvm, but I can confirm that it builds locally when building against the patched llvm.

**Comment by SylvainCorlay** [comment]
The build times out because we now have two variants of the package which was already long to build.

**Comment by SylvainCorlay** [comment]
So the build still times out, but it has almost completed (built everything, testing the last package). I wonder how I can get under the 120min.

**Comment by SylvainCorlay** [comment]
I have reduced the amount of testing in the case of the `cling` variant to try to pass under the 120 minutes build time.

**Pull request merged**
