### PR TITLE
Add python bindings

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
The ARM and POWER timeouts are also present on master so I think this is ready.

xref: https://github.com/conda-forge/staged-recipes/pull/8178 https://github.com/conda-forge/python-clang-feedstock/pull/1

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by gartung** [comment]
@chrisburr Does this mean I don't need the stand-alone python-clang on macOS. I am having issues using cindex right now because the python-clang version does not match the clangdev version.

**Comment by chrisburr** [comment]
My guess is that `clang` (the default macOS compiler and runtime dependency of ROOT) is conflicting with `clangdev`. Try depending on `python-clang=4` on macOS.

**Pull request merged**
