### PR TITLE
LLVM 15.0.0.rc2

### PR DESCRIPTION
**Pull request by h-vetinari**
Most relevant is that the versioned libclang is [gone](https://github.com/llvm/llvm-project/blob/llvmorg-15.0.0-rc2/clang/docs/ReleaseNotes.rst#libclang) again.

### CODE REVIEW

**Comment by isuruf** [comment]
> Most relevant is that the versioned libclang is [gone](https://github.com/llvm/llvm-project/blob/llvmorg-15.0.0-rc2/clang/docs/ReleaseNotes.rst#libclang) again.

That's a shame. This means we'll have to go for rebuilding qt against each major version of libclang instead of only once.

**Comment by h-vetinari** [comment]
> > Most relevant is that the versioned libclang is [gone](https://github.com/llvm/llvm-project/blob/llvmorg-15.0.0-rc2/clang/docs/ReleaseNotes.rst#libclang) again.
> 
> That's a shame. This means we'll have to go for rebuilding qt against each major version of libclang instead of only once.

You can comment in the [PR](https://reviews.llvm.org/D129160) that changed it or on discourse. I guess there's still a small window where this might be reconsidered, but once LLVM 15 is out, the appetite to change back to versioned _again_  (after going forth and back in LLVM 14 & 15) will probably be out of the question for a while.

**Comment by h-vetinari** [comment]
> You can comment in the [PR](https://reviews.llvm.org/D129160) that changed it or on discourse.

I saw you commented on the PR, but realistically there's only a handful of people there, and Tom Stellard is currently away (at least he passed on his RM duties). You'll probably have more chances of success (or at least a wider audience) on [discourse](https://discourse.llvm.org/) (which fully replaced their mailing lists).

**Comment by isuruf** [comment]
Do you have some time to do that? I don't know if I'll be able to find the time.

**Comment by h-vetinari** [comment]
> Do you have some time to do that? I don't know if I'll be able to find the time.

Don't know if I'll be a good spokesperson for your concerns, but I can past your question.

**Comment by h-vetinari** [comment]
> > Do you have some time to do that? I don't know if I'll be able to find the time.
> 
> Don't know if I'll be a good spokesperson for your concerns, but I can paste your question.

[Done](https://discourse.llvm.org/t/rationale-for-removing-versioned-libclang-middle-ground-to-keep-it-behind-option/64410)

**Comment by h-vetinari** [comment]
> Do you have some time to do that? I don't know if I'll be able to find the time.

I had posted to the LLVM discourse, and after some discussion, we now arrived at a [PR](https://reviews.llvm.org/D132486) (based on changes I proposed), but it's receiving pretty strong pushback both on phabricator and now also on discourse, and the time for 15.0.0-rc3 is running low (though the interim release manager has extended the release partially for this).

In any case, I don't think more answers from my side will shift the balance, so I've taken this as far as I could. If you'd like to have this feature back, I think the best way is to get involved in the conversation.

**Pull request merged**
