### PR TITLE
link clang tools extra against libclang

### PR DESCRIPTION
**Pull request by timsnyder**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Requested by @isuruf in https://github.com/conda-forge/clangdev-feedstock/pull/64#issuecomment-538787084

### CODE REVIEW

**Comment by timsnyder** [comment]
@isuruf, looks like the patch you pointed to doesn't apply cleanly.  I see that 10.0.0 is in the works now.  Is it worth spending time to get this to apply and work for 9.x or should we just wait for 10.x?

**Comment by jakirkham** [comment]
If it’s not already in 9, it seems worthwhile. I thought that was what your original PR did though or am I misreading things?

**Comment by timsnyder** [comment]
> If it’s not already in 9, it seems worthwhile. I thought that was what your original PR did though or am I misreading things?

#64 added clang-tools-extra to clang-tools.  This PR is a followon that Issuru asked for at the end of #64.  I'll go ahead and cleanup the patch.

**Comment by jakirkham** [comment]
Ah ok. I may have missed that. Sorry

**Comment by timsnyder** [comment]
Hmm.  Even after getting the patch cleaned up, for some reason the package tests fail.  I'm going to build osx locally and see more detail about how the tests are failing.

**Comment by isuruf** [comment]
@timsnyder, don't spend too much time on this. Update to 10.0.0 is more important.

**Comment by timsnyder** [comment]
I'm abandoning this in favor of just updating to 10.0.

**Pull request closed without merging**
