### PR TITLE
Build 13.0.1-rc1

### PR DESCRIPTION
**Pull request by h-vetinari**
Continuing from https://github.com/conda-forge/llvmdev-feedstock/pull/134

### CODE REVIEW

**Comment by h-vetinari** [comment]
@wolfv, has mamba run through `label/rc` PRs successfully already? The llvmdev packages should have the right [label](https://github.com/conda-forge/llvmdev-feedstock/blob/rc/recipe/conda_build_config.yaml#L2); this PR is using the same channel-source as the `rc` branch did [previously](https://github.com/conda-forge/clangdev-feedstock/blob/rc/recipe/conda_build_config.yaml#L31); however package discovery fails, and curiously, I cannot actually see what channels mamba uses because the log is empty on that:
```
Mamba failed to solve:
 - llvmdev 13.0.1.rc1
 - zlib 1.2.*
 - zlib

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested llvmdev 13.0.1.rc1
```

**Comment by h-vetinari** [comment]
@conda-forge/clangdev 

No idea what's driving up the OSX compile time so badly (perhaps just a very slow agent), but IMO this is ready.

**Comment by xhochy** [comment]
Can you try to use `lief_dev` as we do in Tensorflow? Could be that the long times stem from there?

**Comment by h-vetinari** [comment]
Unfortunately no change with `lief_dev`. I have to say it's a crazy kind of compile time regression, which is especially surprising given that it's a patch release. 13.0.0 [compiled](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=417649&view=results) in 3h on OSX (incl. all the conda-stuff), now 6h are not enough for 13.0.1...

**Comment by h-vetinari** [comment]
> Could be that the long times stem from there?

In case it helps, I heavily redacted the raw log from the last run to get some idea about where the time is spent:
```
2022-01-08T18:15:44.5632830Z ##[section]Starting: Run OSX build
2022-01-08T18:21:55.8820450Z BUILD START: ['libclang-cpp13-13.0.1.rc1-default_haeb2ba7_0.tar.bz2', 'clang-13-13.0.1.rc1-default_haeb2ba7_0.tar.bz2', 'libclang-cpp-13.0.1.rc1-default_haeb2ba7_0.tar.bz2', 'clang-13.0.1.rc1-h9d310f0_0.tar.bz2', 'clangxx-13.0.1.rc1-default_haeb2ba7_0.tar.bz2', 'libclang-13.0.1.rc1-default_haeb2ba7_0.tar.bz2', 'clang-format-13-13.0.1.rc1-default_haeb2ba7_0.tar.bz2', 'python-clang-13.0.1.rc1-default_h53e2bf8_0.tar.bz2', 'clang-format-13.0.1.rc1-default_haeb2ba7_0.tar.bz2', 'clang-tools-13.0.1.rc1-default_haeb2ba7_0.tar.bz2', 'clangdev-13.0.1.rc1-default_haeb2ba7_0.tar.bz2']
2022-01-08T18:22:17.8082680Z Downloading source to cache: clang-13.0.1rc1.src_c8359a51f7.tar.xz
                             # run global build.sh
2022-01-08T18:22:56.3538240Z -- Build files have been written to: $SRC_DIR/build
2022-01-08T18:27:01.3217030Z [ 20%] Building CXX object lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/AMDGPU.cpp.o
2022-01-08T18:48:57.2535570Z [ 40%] Building CXX object lib/Tooling/CMakeFiles/obj.clangTooling.dir/ArgumentsAdjusters.cpp.o
2022-01-08T19:19:12.9702020Z [ 60%] Building CXX object tools/extra/clang-tidy/cppcoreguidelines/CMakeFiles/obj.clangTidyCppCoreGuidelinesModule.dir/ProTypeVarargCheck.cpp.o
2022-01-08T19:54:53.3671260Z [ 80%] Building CXX object tools/extra/clangd/CMakeFiles/obj.clangDaemon.dir/index/Background.cpp.o
2022-01-08T20:14:12.2944140Z Resource usage statistics from building clang_packages:
                             # output libclang-cpp13
2022-01-08T20:14:12.3340680Z Packaging libclang-cpp13
2022-01-08T20:14:25.0856170Z + make install VERBOSE=1
2022-01-08T20:14:31.2860300Z [ 20%] Built target obj.clangLex
2022-01-08T20:14:35.8022880Z [ 40%] Built target obj.clangDriver
2022-01-08T20:14:41.3154150Z [ 61%] Built target obj.clangStaticAnalyzerCheckers
2022-01-08T20:14:49.0701590Z [ 81%] Built target obj.clangTidyModernizeModule
2022-01-08T20:15:07.7668420Z Resource usage statistics from bundling libclang-cpp13:
                             # output clang-13
2022-01-08T20:15:27.9990750Z Packaging clang-13
2022-01-08T20:15:43.9010320Z + make install
2022-01-08T20:17:39.5457640Z [ 11%] Built target clang-resource-headers
2022-01-08T20:21:26.6836750Z [ 20%] Building CXX object lib/Lex/CMakeFiles/obj.clangLex.dir/PPCallbacks.cpp.o
2022-01-08T20:50:10.5079690Z [ 30%] Building CXX object lib/Sema/CMakeFiles/obj.clangSema.dir/SemaStmtAttr.cpp.o
2022-01-08T21:04:36.0241200Z [ 40%] Building CXX object lib/Driver/CMakeFiles/obj.clangDriver.dir/XRayArgs.cpp.o
2022-01-08T21:34:11.7716450Z [ 50%] Building CXX object lib/Tooling/CMakeFiles/obj.clangTooling.dir/ArgumentsAdjusters.cpp.o
2022-01-08T22:04:12.7067450Z [ 60%] Building CXX object lib/StaticAnalyzer/Checkers/CMakeFiles/obj.clangStaticAnalyzerCheckers.dir/StreamChecker.cpp.o
2022-01-08T22:19:33.0678520Z [ 70%] Building CXX object tools/extra/clang-tidy/utils/CMakeFiles/obj.clangTidyUtils.dir/ExceptionAnalyzer.cpp.o
2022-01-08T22:49:45.8863150Z [ 80%] Building CXX object tools/extra/clang-tidy/modernize/CMakeFiles/obj.clangTidyModernizeModule.dir/DeprecatedHeadersCheck.cpp.o
2022-01-08T23:26:08.7426190Z [ 90%] Building CXX object tools/extra/clang-doc/CMakeFiles/obj.clangDoc.dir/HTMLGenerator.cpp.o
2022-01-08T23:48:48.0036370Z Resource usage statistics from bundling clang-13:
                             # output libclang-cpp
2022-01-08T23:49:00.2342030Z Packaging libclang-cpp
2022-01-08T23:49:12.7563210Z + make install VERBOSE=1
2022-01-08T23:54:47.6936680Z [ 20%] Building CXX object lib/Lex/CMakeFiles/obj.clangLex.dir/PPCallbacks.cpp.o
2022-01-09T00:15:38.4839250Z [ 28%] Building CXX object lib/Sema/CMakeFiles/obj.clangSema.dir/SemaDecl.cpp.o
2022-01-09T00:15:47.2889080Z ##[error]The operation was canceled.
2022-01-09T00:15:47.2905760Z ##[section]Finishing: Run OSX build
```

It's worth noting that at this point, we still have many outputs left (see second line above):
* ~`build.sh`~
* ~`'libclang-cpp13-13.0.1.rc1-default_haeb2ba7_0.tar.bz2'`~
* ~`'clang-13-13.0.1.rc1-default_haeb2ba7_0.tar.bz2'`~
* `'libclang-cpp-13.0.1.rc1-default_haeb2ba7_0.tar.bz2'`
* `'clang-13.0.1.rc1-h9d310f0_0.tar.bz2'`
* `'clangxx-13.0.1.rc1-default_haeb2ba7_0.tar.bz2'`
* `'libclang-13.0.1.rc1-default_haeb2ba7_0.tar.bz2'`
* `'clang-format-13-13.0.1.rc1-default_haeb2ba7_0.tar.bz2'`
* `'python-clang-13.0.1.rc1-default_h53e2bf8_0.tar.bz2'`
* `'clang-format-13.0.1.rc1-default_haeb2ba7_0.tar.bz2'`
* `'clang-tools-13.0.1.rc1-default_haeb2ba7_0.tar.bz2'`
* `'clangdev-13.0.1.rc1-default_haeb2ba7_0.tar.bz2'`

**Comment by h-vetinari** [comment]
So on OSX, packaging `clang-13` now needs 3.5h, whereas on linux, it takes 40 seconds!
```
20:08:04 Packaging clang-13
20:08:44 Packaging libclang-cpp
```

Could it be that something from `build.sh` is not picked up correctly when processing the outputs?

**Comment by isuruf** [comment]
Fixed now. I marked as clang_bootstrap 11.rc builds as broken to avoid different compilers in top level build vs output level build envs which caused make to recompile.

**Comment by h-vetinari** [comment]
Awesome, thanks! Glad this could be resolved. So then there should be no impediment to merging anymore?

**Comment by h-vetinari** [comment]
I don't see any packages uploaded for this... Is there a reason that the CI didn't seem to trigger.

**Pull request merged**
