### PR TITLE
Add the flang variant

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by xoviat** [comment]
@conda-forge-admin Please rerender

**Comment by xoviat** [comment]
@conda-forge-admin Please rerender.

**Comment by xoviat** [comment]
Seems the conda-forge recipe failed. Not sure why.

**Comment by isuruf** [comment]
I think this should be better in a another branch, as flang's clang does not have a release cycle matching llvm's clang.

**Comment by xoviat** [comment]
Another repository or another branch? I cannot create a branch in this repository.

**Comment by isuruf** [comment]
@jakirkham, @inducer can you create a new branch?

**Comment by xoviat** [comment]
Closing as will re-do after branch is added.

**Pull request closed without merging**
