### PR TITLE
[16.x] Add root variant to track_features

### PR DESCRIPTION
**Pull request by vepadulano**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by vepadulano** [comment]
As requested at https://github.com/conda-forge/clangdev-feedstock/issues/265

**Review by h-vetinari — APPROVED** [review]
Thanks for the quick response!

**Comment by h-vetinari** [comment]
Can you please bump the build number as well?

**Comment by vepadulano** [comment]
> Can you please bump the build number as well?

Sure! Apologies as I am still not sure about which changes need to trigger a bump in the build number (I guess anything that requires a rerender maybe?)

**Pull request merged**
