### PR TITLE
Clean up dependencies

### PR DESCRIPTION
**Pull request by h-vetinari**

### CODE REVIEW

**Comment by isuruf** [comment]
Can we please keep `make`? ninja's verbose mode gives very little info and recent llvmdev-feedstock issue would have been easier to debug if we used make.

**Comment by h-vetinari** [comment]
> Can we please keep `make`? ninja's verbose mode gives very little info and recent llvmdev-feedstock issue would have been easier to debug if we used make.

OK, if you have that preference, I don't mind.

(by default, I try to harmonize the build system across platforms with ninja where possible; one less divergence to handle).

**Comment by h-vetinari** [comment]
Hm, seems the `NATIVE_FLAGS` here aren't being picked up correctly, or rather, the lack of `ZSTD_ROOT` / `LIBXML2_ROOT` in https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0-rc4/llvm/cmake/modules/LLVMConfig.cmake.in#L70-L84 leads to the one from the host prefix being found:
```
-- Detecting CXX compile features - done
-- Found ZLIB: $BUILD_PREFIX/lib/libz.so (found version "1.2.13")  
-- Found zstd: $PREFIX/lib/libzstd.so  
-- Found LibXml2: $PREFIX/lib/libxml2.so (found version "2.10.3") 
```

**Comment by h-vetinari** [comment]
Thanks for the help with https://github.com/conda-forge/clangdev-feedstock/pull/205/commits/367a295ae33ad389699b0b69dff7cb971d25fb97 Isuru, much better than what I was trying to do in https://github.com/conda-forge/llvmdev-feedstock/pull/204, obviously.

I've looked a bit more closely how the native config is being built in upstream cross-compilation, and it's basically a normal CMake invocation; this also explains why `CMAKE_PREFIX_PATH` works out-of-the-box.

In any case, this should now be more consistent, both internally and with our llvmdev builds.

There shouldn't be any surprises here, but let me know if you want some time to review at your leisure.

**Comment by h-vetinari** [comment]
Included in #206

**Pull request closed without merging**
