### PR TITLE
Update to 4.0

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by inducer** [comment]
@SylvainCorlay Here's a first test balloon for Clang 4.0. I've disabled the cling patches for the time being. If you would like to keep them, it'd be great if you could look into porting them over.

**Comment by SylvainCorlay** [comment]
ok, thanks for the heads up.

**Comment by inducer** [comment]
I don't understand what's going on here--summoning @conda-forge/core. :)

The Circle Linux build fails with

```
/opt/rh/devtoolset-2/root/..../ld:
warning: libicui18n.so.58, needed by 
/feedstock_root/build_artefacts/clangdev_1495735277882/..../lib/libxml2.so, not found (try using -rpath or -rpath-link)
```

This is confusing because 

```
    icu:             58.1-1          conda-forge (copy)
```

is installed before the build. I saw that there was some issue with icu/libxml2 and was wondering whether this might be related. @jakirkham also messed with libxml2 versions in the (thus far) unmerged #9.

I'd be grateful for any help. Thanks!

**Comment by jakirkham** [comment]
> @jakirkham also messed with libxml2 versions in the (thus far) unmerged #9.

😕 That was the pinning bot. Only noted the bot forgot a build number bump.

**Pull request merged**
