### PR TITLE
Build 5.x for osx-arm64

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge/clangdev It think it's almost impossible to cross-compile `clangdev 5` for `osx-arm64` as there is a conflict in the build environment between `llvmdev=5` and `clangxx_osx-arm64=11.0.0` due to the mutual dependence on the same `llvm-tools` version.

I've tried using `conda create` to make a second build environment with `llvmdev 5` but it then gets lost in linker errors. While I can probably fix them with enough effort I'm not conviced it's worth it.

Instead I propose I'll build them locally on native hardware and upload them following the procedure in [CFEP-03](https://github.com/conda-forge/cfep/blob/master/cfep-03.md). If there are no objections I'll do it soon and paste the logs. I've already ran local tests and it works as expected for the root variant. I'll also do the cling variant if possible.

**Comment by isuruf** [comment]
what linker errors?

**Comment by chrisburr** [comment]
I've pushed that version of this PR and you can find a finished CI log below. I think the issue is just that it's mixing up the environments and linking against the wrong LLVM. If you'd rather I go down the `conda create llvmdev=5 --prefix=$SRC_DIR/native-llvm5` route I can dig deeper.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=250177&view=logs&jobId=0d8c2066-2201-5f19-3838-f053fa1bd053&j=0d8c2066-2201-5f19-3838-f053fa1bd053&t=a79f06a2-44be-5d55-7b88-9db4d9dacad4

**Comment by chrisburr** [comment]
I think I've managed to figure it out 🤞

**Pull request merged**
