### PR TITLE
backport clang-tools-extra to 8.x

### LINKED ISSUE #79: Backporting Extra Clang Tools to Clang 8
It would be useful to add Extra Clang Tools to Clang 8 for things still on 8 (like Numba, CUDA, etc.). This would likely amount to backporting PR ( https://github.com/conda-forge/clangdev-feedstock/pull/64 ).

### PR DESCRIPTION
**Pull request by timsnyder**
DO NOT MERGE to master.  This should be pulled as a new `8.x` branch.  I don't how github allows creation of a new branch in the upstream via a PR.  If you guys create a `8.x` branch from 61fde7f254fcc8421a9cbfa9cbe5398cab2363e6, I can recreate this PR to use that as the base.

This adds clang-tools-extra to clang-tools for 8.x as we did for 9.x in #64.  Requested by @jakirkham in https://github.com/conda-forge/clangdev-feedstock/pull/64#issuecomment-603641265

Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #79

### CODE REVIEW

**Comment by timsnyder** [comment]
Hmm.  I guess the CI won't even try to run if there are merge conflicts.  I need someone in @conda-forge/clangdev an `8.x` branch at 61fde7f254fcc8421a9cbfa9cbe5398cab2363e6 that I can base this PR on.  

I guess an empty commit with `[skip_ci] [ci_skip]` tags in the beginning of the commit message will prevent it from running a bogus CI build and let me reopen this?

**Comment by jakirkham** [comment]
Thanks Tim! 😄

Done and have retargeted this PR too `8.x` as well. Please let me know if you need anything else 😉

**Comment by timsnyder** [comment]
osx_ failure on AP looks like a transient http issue while trying to clone the source repo.  closing and reopening to kick the CI  to retry.

**Comment by jakirkham** [comment]
Indeed and AppVeyor is not relevant here. Going to go ahead and merge. Thanks @timsnyder! 😄

**Pull request merged**
